AWSTemplateFormatVersion: '2010-09-09'
Description: Generic EC2 role with allowed ssm, codedeploy, cloudwatch agents

Resources:

  EC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: S3ListAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:ListAllMyBuckets
                  - s3:ListBucketMultipartUploads
                  - s3:ListBucketVersions
                  - s3:ListJobs
                Resource:
                  - "arn:aws:s3:::aws4you-artifacts"
        - PolicyName: S3GetObjectsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListMultipartUploadParts
                Resource:
                  - "arn:aws:s3:::aws4you-artifacts/web-backend-pipeline/*"
                  - "arn:aws:s3:::aws4you-artifacts/web-backend-prod/*"
        - PolicyName: S3WriteObjectsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - "arn:aws:s3:::aws4you-artifacts/dbbackup/*"
        - PolicyName: TagVolumes
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:DescribeInstances"
                  - "ec2:CreateTags"
                Resource: '*'
        - PolicyName: Certbot
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "route53:ListHostedZones"
                  - "route53:GetChange"
                Resource: '*'
              - Effect: Allow
                Action:
                  - "route53:ChangeResourceRecordSets"
                Resource: 'arn:aws:route53:::hostedzone/Z100449812MXZTBZTVSUT'
      Path: /

Outputs:

  EC2GenericRole:
    Description: Generic EC2 role with allowed ssm, codedeploy, cloudwatch agents
    Value: !GetAtt EC2InstanceRole.Arn

  EC2GenericRoleArn:
    Description: Generic EC2 role ARN with allowed ssm, codedeploy, cloudwatch agents
    Value: !Ref EC2InstanceRole

